set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(TOOLCHAIN_ROOT "/run/media/nixxo/data/mingw32/mingw32/mingw32_686-msvcrt_win98-15")

set(CMAKE_C_COMPILER "${TOOLCHAIN_ROOT}/bin/i686-w64-mingw32-gcc-wrapper")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_ROOT}/bin/i686-w64-mingw32-g++-wrapper")
set(CMAKE_RC_COMPILER "${TOOLCHAIN_ROOT}/bin/i686-w64-mingw32-windres-wrapper")

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_ROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)